### ISSUE TITLE
Dockerfile errors

### ISSUE THREAD

**Issue by Avdbergnmf** [DLopezMadrid/pcl-docker#1]
Hey man, I'm trying to adopt this repo for usage with [GPD](https://github.com/atenpas/gpd), more specifically [GPD ROS](https://github.com/atenpas/gpd_ros/). However, I've ran into some issues with the Dockerfile. I thought I'd report them here, in case you want to fix them (or tell me I'm wrong, and they're not mistakes :P)

- instead of `-j$(nproc)`, you sometimes put `-j12` for the make command. This crashes the compiler for me, as I don't have 12 cores :P. Changing it to `-j$(nproc)`, or `-j4` (I do have 4 cores) fixes this.
- On the OpenCV part you set the CMAKE_BUILD_TYZZPE flag, which I don't believe exists, and you probably meant to set CMAKE_BUILD_TYPE.

**Comment by DLopezMadrid** [comment]
Hi, you are totally right, I will fix those things. 
For the 2nd point it is clearly me trying to save the file with vim and not realizing that I was in edit mode. Thanks a lot for opening the issue!
